[package]
name = "SS-Signer"
version = "0.1.0"
edition = "2021"

[dependencies]
rand_core = "0.6.4"
sha2 = "0.10.8"
k256 = "0.13.4"
silentpayments = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4.3"
bitcoin = "0.32.4"